### ISSUE TITLE
{{{flash}}} layout usage in ejs template

### ISSUE THREAD

**Issue by dewelloper** [carlosascari/express-flash-notification#1]
how can i add the body flash in ejs

<<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    {{{flash}}}
</body>
</html>

in my case layout like below

<!DOCTYPE html>
<html lang="en">
<head>

<script type="jscript" src='/javascripts/jquery.min.js'></script>
<link rel="stylesheet" type="text/css" href='/stylesheets/style.css'>
<link rel="stylesheet" type="text/css" href='/stylesheets/bootstrap.min.css'>

</head>
<body>
    <% include partials/head.ejs %>   
    <% include partials/header.ejs %>
    <div class="container">
        <div class="starter-template">
            <%- body %>
        </div>
    </div>
    <% include partials/footer.ejs %>
</body>

</html>

please help me

**Comment by carlosascari** [comment]
Hi @dewelloper, 

Instead using `{{{flash}}}` in your layout use: `<%- locals.flash %>`
Instead of using `{{type}}` in your flash.ejs file, use: `<%= locals.flash %>`

I've created [express-flash-notification-example](https://github.com/carlosascari/express-flash-notification-example), inside you will find a ejs setup commented out in the `server.js`, uncomment that and comment out the mustache setup also in `server.js` to see it working.

Cheers!
